grails-app/domain/arquitetura/bug/SituacaoBug.groovy
package arquitetura.bug

class SituacaoBug {

    transient mensagemService

    String label
    boolean fechado

    static transients = ['mensagemService']

    static constraints = {
        label nullable: false, blank: false, maxSize: 200
    }

    static namedQueries = {
        emAndamento {
            eq 'label', 'situacaoBug.aberto.label'
            maxResults 1
        }
    }

    String toString() {
        mensagemService.traduzir(label)
    }
}

grails-app/controllers/arquitetura/bug/SituacaoBugController.groovy
package arquitetura.bug

import base.BaseController

class SituacaoBugController extends BaseController<SituacaoBug> {

    def getAtributoQuandoSalvoOuExcluido(def Object instancia) {
        return instancia.label
    }
}

grails-app/views/situacaoBug/_form.gsp
<%@ page import="arquitetura.bug.SituacaoBug" %>



<div class="form-group">
	<label for="label" class="col-lg-2 control-label">
		<g:message code="situacaoBug.label.label" default="Label"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="label" maxlength="200" required="" value="${situacaoBugInstance?.label}"/>

	</div>
</div>

<div class="form-group">
	<label for="fechado" class="col-lg-2 control-label">
		<g:message code="situacaoBug.fechado.label" default="Fechado"/>
		
	</label>
	<div class="col-lg-4">
		<will:checkBox name="fechado" value="${situacaoBugInstance?.fechado}" />

	</div>
</div>

grails-app/views/situacaoBug/create.gsp
<%@ page import="arquitetura.bug.SituacaoBug" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="create">
		<g:set var="entityName" value="${message(code: 'situacaoBug.label', default: 'SituacaoBug')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'situacaoBug.plural.label', default: 'SituacaoBug')}" scope="request" />
		<g:set var="instancia" value="${situacaoBugInstance}" scope="request" />
		<title><g:message code="default.create.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:render template="form"/>
	</body>
</html>

grails-app/views/situacaoBug/edit.gsp
<%@ page import="arquitetura.bug.SituacaoBug" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="edit">
		<g:set var="entityName" value="${message(code: 'situacaoBug.label', default: 'SituacaoBug')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'situacaoBug.plural.label', default: 'SituacaoBug')}" scope="request" />
		<g:set var="instancia" value="${situacaoBugInstance}" scope="request" />
		<title><g:message code="default.edit.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:hiddenField name="id" value="${situacaoBugInstance?.id}" />
		<g:hiddenField name="version" value="${situacaoBugInstance?.version}" />
		<g:render template="form"/>
	</body>
</html>

grails-app/views/situacaoBug/list.gsp
<%@ page import="arquitetura.bug.SituacaoBug" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="list">
		<g:set var="entityName" value="${message(code: 'situacaoBug.label', default: 'SituacaoBug')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'situacaoBug.plural.label', default: 'SituacaoBugs')}" scope="request" />
		<g:set var="domainName" value="arquitetura.bug.SituacaoBug" scope="request" />
		%{--<g:set var="filterProperties" value=""/>--}%
		<title><g:message code="default.list.label" args="[entityNamePlural]" /></title>
	</head>

	<body>
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						
						<g:sortableColumn property="label" title="${message(code: 'situacaoBug.label.label', default: 'Label')}" />
						
						<g:sortableColumn property="fechado" title="${message(code: 'situacaoBug.fechado.label', default: 'Fechado')}" />
						
						<th class="acoes"><g:message code="sistema.acoes.label" /> </th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${situacaoBugInstanceList}" status="i" var="situacaoBugInstance">
					<tr>
						
						<td>
							<g:link action="show" id="${situacaoBugInstance.id}"><g:message code="${situacaoBugInstance.label}" /></g:link>
							<will:editI18nButton tituloPopup="situacaoBug.titulo.label" label="${situacaoBugInstance.label}" controllerRetorno="situacaoBug" id="${situacaoBugInstance.id}" />
						</td>
						
						<td><g:formatBoolean boolean="${situacaoBugInstance.fechado}" /></td>
						
						<td class="acoes">
							<will:editLink id="${situacaoBugInstance.id}" />
							<will:deleteConfirmButton id="${situacaoBugInstance.id}" />
						</td>
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>

		<div class="pagination">
			<g:paginate total="${situacaoBugInstanceCount}" params="${filterParams}"/>
		</div>
	</body>
</html>

grails-app/views/situacaoBug/show.gsp
<%@ page import="arquitetura.bug.SituacaoBug" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="show">
	<g:set var="entityName" value="${message(code: 'situacaoBug.label', default: 'SituacaoBug')}" scope="request" />
	<g:set var="entityNamePlural" value="${message(code: 'situacaoBug.plural.label', default: 'SituacaoBugs')}" scope="request" />
	<g:set var="instancia" value="${situacaoBugInstance}" scope="request" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="situacaoBug.label.label" default="Label" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${situacaoBugInstance}" field="label"/>
				
			</p>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="situacaoBug.fechado.label" default="Fechado" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:formatBoolean boolean="${situacaoBugInstance?.fechado}" />
				
			</p>
		</div>
	</div>
	
</body>
</html>