grails-app/domain/arquitetura/seguranca/Usuario.groovy
package arquitetura.seguranca

class Usuario {

    transient springSecurityService

    String nomeCompleto
    String username
    String email
    String password
    boolean enabled = true
    boolean accountExpired
    boolean accountLocked
    boolean passwordExpired

    static hasMany = [oAuthIDs: OAuthID]

    static transients = ['springSecurityService']

    static constraints = {
        username blank: false, unique: true
        password nullable: false, blank: false
        nomeCompleto blank: false
        email blank: false, email: true
    }

    static mapping = {
        password column: '`password`'
    }

    Set<Papel> getAuthorities() {
        Permissao.findAllByUsuario(this).collect { it.papel }
    }

    def beforeInsert() {
        encodePassword()
    }

    def beforeUpdate() {
        if (isDirty('password')) {
            encodePassword()
        }
    }

    def beforeDelete() {
        Permissao.removeAll(this)
    }

    protected void encodePassword() {
        password = springSecurityService?.passwordEncoder ? springSecurityService.encodePassword(password) : password
    }
}

grails-app/controllers/arquitetura/seguranca/UsuarioController.groovy
package arquitetura.seguranca

import arquitetura.command.UsuarioCommand
import base.BaseController
import utils.TratadorDeParametros

class UsuarioController extends BaseController<Usuario> {

    def usuarioService
    def springSecurityService

    def getAtributoQuandoSalvoOuExcluido(instancia) {
        return instancia.username
    }

    def create() {
        [usuarioInstance: new UsuarioCommand()]
    }

    def edit() {
        prepararCommand()
    }

    def save(UsuarioCommand command) {
        internalSave(command, 'create', 'default.created.message')
    }

    def update(UsuarioCommand command) {
        command.alteracao = true
        internalSave(command, 'edit', 'default.updated.message')
    }

    private def internalSave(UsuarioCommand command, String view, String mensagem) {
        command.id = TratadorDeParametros.somenteNumerosLong(params.id)
        command.versao = TratadorDeParametros.somenteNumerosLong(params.versao)
        usuarioService.salvarUsuario(command)
        if (command.hasErrors()) {
            render view: view, model: [usuarioInstance: command]
            return
        }

        flash.message = message(code: mensagem, args: [message(code: "usuario.label", default: "Usuario"), getAtributoQuandoSalvoOuExcluido(command)])
        redirect(action: "list")
    }

    def show() {
        prepararCommand()
    }

    def alternar() {
        Usuario usuario = usuarioService.alternarCampo(TratadorDeParametros.somenteNumerosLong(params.id), params.campo, params.versao)
        if (usuario.hasErrors()) {
            params.errors = usuario.errors.allErrors
        } else {
            flash.message = message(code: 'usuario.alternar.sucesso.message', args: [message(code: "usuario.${params.campo}.label", default: 'Campo')])
        }
        forward(action: 'list')
    }

    def permissoesPopup() {
        prepararCommand()
    }

    def salvarPermissoes(UsuarioCommand command) {
        Usuario usuario = find()
        usuarioService.salvarPermissoes(command, usuario)
        if (command.hasErrors()) {
            render view: 'permissoesPopup', model: [usuarioInstance: command]
        } else {
            render view: '/layouts/texto', model: [mensagem: message(code: 'usuario.permissoes.sucesso.message')]
        }

    }

    def minhaConta() {
        prepararCommand()
    }

    def alterarSenhaPopup() {
        prepararCommand()
    }

    def alterarSenha(UsuarioCommand command) {
        command.id = TratadorDeParametros.somenteNumerosLong(params.id)
        command.versao = TratadorDeParametros.somenteNumerosLong(params.versao)
        usuarioService.alterarSenha(command)
        if (command.hasErrors()) {
            render view: 'alterarSenhaPopup', model: [usuarioInstance: command]
        } else {
            render view: '/layouts/texto', model: [mensagem: message(code: 'usuario.senhaAlterada.message')]
        }
    }

    def registro() {
        return [usuarioInstance: new UsuarioCommand(email: params.email, nomeCompleto: params.nomeCompleto)]
    }

    def registrar(UsuarioCommand command) {
        usuarioService.registrar(command, session['oAuthID'])
        if (command.hasErrors()) {
            render view: 'registro', model: [usuarioInstance: command]
        } else {
            session.removeAttribute('oAuthID')
            springSecurityService.reauthenticate(command.email)
            redirect(controller: 'login', params: [message: message(code: 'usuario.registradoSucesso.message', args: [command.email])])
        }
    }

    private def prepararCommand() {
        [usuarioInstance: usuarioService.criarCommand(TratadorDeParametros.somenteNumerosLong(params.id))]
    }
}

grails-app/views/usuario/_form.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>

<div class="form-group">
	<label for="nomeCompleto" class="col-lg-2 control-label">
		<g:message code="usuario.nomeCompleto.label" default="Nome Completo"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="nomeCompleto" required="" value="${usuarioInstance?.nomeCompleto}"/>
	</div>
</div>

<div class="form-group">
	<label for="email" class="col-lg-2 control-label">
		<g:message code="usuario.email.label" default="Email"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="email" required="" value="${usuarioInstance?.email}"/>
	</div>
</div>

<div class="form-group">
	<label for="username" class="col-lg-2 control-label">
		<g:message code="usuario.username.label" default="Username"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="username" required="" value="${usuarioInstance?.username}"/>
	</div>
</div>

<div class="form-group">
	<label for="password" class="col-lg-2 control-label">
		<g:message code="usuario.password.label" default="Password"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<g:if test="${novo}">
			<will:passwordField name="password" required="" />
		</g:if><g:else>
			<will:passwordField name="password" />
		</g:else>
	</div>
</div>

<div class="form-group">
	<label for="accountExpired" class="col-lg-2 control-label">
		<g:message code="usuario.accountExpired.label" default="Account Expired"/>
	</label>
	<div class="col-lg-4">
		<will:checkBox name="accountExpired" value="${usuarioInstance?.accountExpired}" />
	</div>
</div>

<div class="form-group">
	<label for="accountLocked" class="col-lg-2 control-label">
		<g:message code="usuario.accountLocked.label" default="Account Locked"/>
	</label>
	<div class="col-lg-4">
		<will:checkBox name="accountLocked" value="${usuarioInstance?.accountLocked}" />
	</div>
</div>

<div class="form-group">
	<label for="enabled" class="col-lg-2 control-label">
		<g:message code="usuario.enabled.label" default="Enabled"/>
	</label>
	<div class="col-lg-4">
		<will:checkBox name="enabled" value="${usuarioInstance?.enabled}" />
	</div>
</div>

<div class="form-group">
	<label for="passwordExpired" class="col-lg-2 control-label">
		<g:message code="usuario.passwordExpired.label" default="Password Expired"/>
	</label>
	<div class="col-lg-4">
		<will:checkBox name="passwordExpired" value="${usuarioInstance?.passwordExpired}" />
	</div>
</div>

<div class="form-group">
	<label for="permissoes" class="col-lg-2 control-label">
		<g:message code="usuarioCommand.permissoes.label" default="Permissoes" />
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-6">
		<will:select id="permissoes" name="permissoes" from="${arquitetura.seguranca.Papel.list()}" value="${usuarioInstance?.permissoes?.id}" multiple="multiple" optionKey="id" optionValue="authority" />
	</div>
</div>

grails-app/views/usuario/alterarSenhaPopup.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="popup">
    <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
    <g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuarios')}" />
    <g:set var="instancia" value="${usuarioInstance}" scope="request" />
    <title><g:message code="default.new.label" args="[entityName]" /></title>
</head>
<body>
<div id="create-menu" class="container" role="main">
    <g:form action="salvarPopup" class="form-horizontal" role="form" >
        <g:hiddenField name="id" value="${usuarioInstance?.id}" />
        <g:hiddenField name="versao" value="${usuarioInstance?.versao}" />
        <div class="form-group">
            <label for="password" class="col-lg-2 control-label">
                <g:message code="usuario.senhaAtual.label" default="Password" />
                <span class="required-indicator">*</span>
            </label>
            <div class="col-lg-4">
                <will:passwordField name="password" required="" />
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-lg-2 control-label">
                <g:message code="usuario.novaSenha.label" default="Password" />
                <span class="required-indicator">*</span>
            </label>
            <div class="col-lg-4">
                <will:passwordField name="novaSenha" required="" />
            </div>
        </div>
        <div class="form-group">
            <label for="password" class="col-lg-2 control-label">
                <g:message code="usuario.confirmacaoSenha.label" default="Password" />
                <span class="required-indicator">*</span>
            </label>
            <div class="col-lg-4">
                <will:passwordField name="confirmacaoSenha" required="" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <will:submitButton action="alterarSenha" />
            </div>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/usuario/create.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="create">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuario')}" scope="request" />
		<g:set var="instancia" value="${usuarioInstance}" scope="request" />
		<title><g:message code="default.create.label" args="[entityName]"/></title>
	</head>

	<body>
        <g:render template="form"/>
	</body>
</html>

grails-app/views/usuario/edit.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="edit">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuario')}" scope="request" />
		<g:set var="instancia" value="${usuarioInstance}" scope="request" />
		<title><g:message code="default.edit.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:hiddenField name="id" value="${usuarioInstance?.id}" />
		<g:hiddenField name="versao" value="${usuarioInstance?.versao}" />
		<g:render template="form"/>
	</body>
</html>

grails-app/views/usuario/list.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="list">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuarios')}" scope="request" />
		<g:set var="domainName" value="arquitetura.seguranca.Usuario" scope="request" />
		%{--<g:set var="filterProperties" value=""/>--}%
		<title><g:message code="default.list.label" args="[entityNamePlural]" /></title>
		<script type="text/javascript">

		</script>
	</head>

	<body>
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<thead>
					<tr>

						<g:sortableColumn property="username"
										  title="${message(code: 'usuario.username.label', default: 'Username')}"/>

						<g:sortableColumn property="accountExpired"
										  title="${message(code: 'usuario.accountExpired.label', default: 'Account Expired')}"/>

						<g:sortableColumn property="accountLocked"
										  title="${message(code: 'usuario.accountLocked.label', default: 'Account Locked')}"/>

						<g:sortableColumn property="enabled"
										  title="${message(code: 'usuario.enabled.label', default: 'Enabled')}"/>

						<g:sortableColumn property="passwordExpired"
										  title="${message(code: 'usuario.passwordExpired.label', default: 'Password Expired')}"/>

						<th><g:message code="sistema.acoes.label"/></th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${usuarioInstanceList}" status="i" var="usuarioInstance">
					<tr>

						<td><g:link action="show"
									id="${usuarioInstance.id}">${fieldValue(bean: usuarioInstance, field: "username")}</g:link></td>

						<td>
							<will:actionButton type="button" class="btn btn-flat acoes btn-${usuarioInstance.accountExpired ? 'danger' : 'success'}" icone="${usuarioInstance.accountExpired ? 'check' : 'times'}" data-toggle="modal" data-target="#expirada${usuarioInstance.id}" title="${message(code: 'usuario.alternar.tooltip')}" />
							<will:confirmacao id="expirada${usuarioInstance.id}"
										   mensagem="${message(code: 'usuario.alternar.confirmar.message', args: [message(code: 'usuario.accountExpired.label', default: 'Account Expired')])}"
										   linkConfirma="${createLink(action: 'alternar', id: usuarioInstance.id, params: [campo: 'accountExpired', versao: usuarioInstance.version])}"/>
						</td>

						<td>
							<will:actionButton type="button" class="btn btn-flat acoes btn-${usuarioInstance.accountLocked ? 'danger' : 'success'}" icone="${usuarioInstance.accountLocked ? 'check' : 'times'}" data-toggle="modal" data-target="#bloqueada${usuarioInstance.id}" title="${message(code: 'usuario.alternar.tooltip')}" />
							<will:confirmacao id="bloqueada${usuarioInstance.id}"
										   mensagem="${message(code: 'usuario.alternar.confirmar.message', args: [message(code: 'usuario.accountLocked.label', default: 'Account Locked')])}"
										   linkConfirma="${createLink(action: 'alternar', id: usuarioInstance.id, params: [campo: 'accountLocked', versao: usuarioInstance.version])}"/>
						</td>

						<td>
							<will:actionButton type="button" class="btn btn-flat acoes btn-${usuarioInstance.enabled ? 'success' : 'danger'}" icone="${usuarioInstance.enabled ? 'check' : 'times'}" data-toggle="modal" data-target="#ativada${usuarioInstance.id}" title="${message(code: 'usuario.alternar.tooltip')}" />
							<will:confirmacao id="ativada${usuarioInstance.id}"
										   mensagem="${message(code: 'usuario.alternar.confirmar.message', args: [message(code: 'usuario.enabled.label', default: 'Enabled')])}"
										   linkConfirma="${createLink(action: 'alternar', id: usuarioInstance.id, params: [campo: 'enabled', versao: usuarioInstance.version])}"/>
						</td>

						<td>
							<will:actionButton type="button" class="btn btn-flat acoes btn-${usuarioInstance.passwordExpired ? 'danger' : 'success'}" icone="${usuarioInstance.passwordExpired ? 'check' : 'times'}" data-toggle="modal" data-target="#senhaExpirada${usuarioInstance.id}" title="${message(code: 'usuario.alternar.tooltip')}" />
							<will:confirmacao id="senhaExpirada${usuarioInstance.id}"
										   mensagem="${message(code: 'usuario.alternar.confirmar.message', args: [message(code: 'usuario.passwordExpired.label', default: 'Password Expired')])}"
										   linkConfirma="${createLink(action: 'alternar', id: usuarioInstance.id, params: [campo: 'passwordExpired', versao: usuarioInstance.version])}"/>
						</td>
						
						<td class="acoes">
							<will:editLink id="${usuarioInstance.id}" />
							<will:deleteConfirmButton id="${usuarioInstance.id}" />
							<will:iframe icone="lock" class="acoes" id="permissoes${usuarioInstance.id}" titulo="${message(code: 'usuarioCommand.permissoes.label')}"
										 linkOk="${createLink(controller: 'usuario', action: 'list', params: params)}"
										 link="${createLink(controller: 'usuario', action: 'permissoesPopup', id: usuarioInstance?.id)}" />
						</td>
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>

		<div class="pagination">
			<g:paginate total="${usuarioInstanceCount}" params="${filterParams}"/>
		</div>
	</body>
</html>

grails-app/views/usuario/minhaConta.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
        <g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuarios')}" />
		<title><g:message code="usuario.minhaConta.label" /></title>
	</head>
	<body>
        <div id="show-cliente" class="container" role="main">
            <g:form class="form-horizontal" role="form" >
                
                <g:if test="${usuarioInstance?.nomeCompleto != null}">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">
                            <g:message code="usuario.nomeCompleto.label" default="nomeCompleto" />
                        </label>
                        <div class="col-lg-4">
                            <p class="form-control-static">
                                
                                <g:fieldValue bean="${usuarioInstance}" field="nomeCompleto"/>
                                
                            </p>
                        </div>
                    </div>
                </g:if>
                
                <g:if test="${usuarioInstance?.email != null}">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">
                            <g:message code="usuario.email.label" default="email" />
                        </label>
                        <div class="col-lg-4">
                            <p class="form-control-static">
                                
                                <g:fieldValue bean="${usuarioInstance}" field="email"/>
                                
                            </p>
                        </div>
                    </div>
                </g:if>
                
                <g:if test="${usuarioInstance?.username != null}">
                    <div class="form-group">
                        <label class="col-lg-2 control-label">
                            <g:message code="usuario.username.label" default="Username" />
                        </label>
                        <div class="col-lg-4">
                            <p class="form-control-static">
                                
                                <g:fieldValue bean="${usuarioInstance}" field="username"/>
                                
                            </p>
                        </div>
                    </div>
                </g:if>

                <div class="form-group">
                    <label class="col-lg-2 control-label">
                        <g:message code="usuario.password.label" default="Password" />
                    </label>
                    <div class="col-lg-4">
                        <div class="col-lg-12">
                        <will:iframe id="senha${usuarioInstance.id}" link="${createLink(controller: 'usuario', action: 'alterarSenhaPopup', id: usuarioInstance?.id)}"
                            icone="pencil" linkOk="${createLink(controller: 'usuario', action: 'minhaConta', id: usuarioInstance.id)}"
                            titulo="${message(code: 'usuario.alterar.senha.label')}" altura="380"><g:message code="usuario.alterar.senha.label" /> </will:iframe>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 control-label">
                        <g:message code="usuario.vincularRedesSociais.label" default="Vincular redes sociais" />
                    </label>
                    <div class="col-lg-4">
                        <div class="col-lg-12">
                            <oauth:connect provider="google" class="btn btn-material-red btn-lg btn-primary"><i class="fa fa-fw fa-google"></i>Google</oauth:connect>
                        </div>
                        <div class="col-lg-12">
                            <oauth:connect provider="twitter" class="btn btn-material-light-blue btn-lg btn-primary"><i class="fa fa-fw fa-twitter"></i>Twitter</oauth:connect>
                        </div>
                        <div class="col-lg-12">
                            <oauth:connect provider="facebook" class="btn btn-material-blue btn-lg btn-primary"><i class="fa fa-fw fa-facebook"></i>Facebook</oauth:connect>
                        </div>
                    </div>
                </div>

                <g:hiddenField name="id" value="${usuarioInstance?.id}" />
			</g:form>
		</div>
	</body>
</html>

grails-app/views/usuario/permissoesPopup.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="popup">
    <g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" />
    <g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuarios')}" />
    <g:set var="instancia" value="${usuarioInstance}" scope="request" />
    <title><g:message code="default.new.label" args="[entityName]" /></title>
</head>
<body>
<div id="create-menu" class="container" role="main">
    <g:form action="salvarPopup" class="form-horizontal" role="form" >
        <g:hiddenField name="id" value="${usuarioInstance?.id}" />
        <g:hiddenField name="versao" value="${usuarioInstance?.versao}" />
        <div class="form-group">
            <label for="permissoes" class="col-lg-2 control-label">
                <g:message code="usuarioCommand.permissoes.label" default="Permissoes" />
            </label>
            <div class="col-lg-6">
                <will:select id="permissoes" name="permissoes" from="${arquitetura.seguranca.Papel.list()}" value="${usuarioInstance?.permissoes?.id}" multiple="multiple" optionKey="id" optionValue="authority" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-10">
                <will:submitButton action="salvarPermissoes" />
            </div>
        </div>
    </g:form>
</div>
</body>
</html>

grails-app/views/usuario/registro.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="login">
    <title><g:message code="sistema.nome.label"/></title>
</head>

<body>
<g:form class="form-horizontal form-signin" role="form" action="registrar" >
    <div class="container" role="main">
        <div class="form-group">
            <div class="col-lg-6">
                <div class="col-lg-12">
                    <h2><g:message code="usuario.registrar.label" /></h2>
                </div>
                <div class="col-lg-12">
                    <will:textField name="nomeCompleto" required="" value="${usuarioInstance?.nomeCompleto}" placeholder="${message(code: 'usuario.nomeCompleto.label')}"/>
                </div>
                <div class="col-lg-12">
                    <will:textField name="email" required="" value="${usuarioInstance?.email}" placeholder="${message(code: 'usuario.email.label')}" email="true"/>
                </div>
                <div class="col-lg-12">
                    <will:passwordField name="novaSenha" required="" placeholder="${message(code: 'usuario.password.label')}" />
                </div>
                <div class="col-lg-12">
                    <will:passwordField name="confirmacaoSenha" required="" placeholder="${message(code: 'usuario.confirmacaoSenha.label')}" />
                </div>
                <div class="col-lg-12">
                    <will:submitButton action="registrar"><g:message code="usuario.registrar.label" /></will:submitButton>
                </div>
            </div>
            <div class="col-lg-6">
                <g:if test="${!session['oAuthID']}">
                    <div class="col-lg-12">
                        <p><g:message code="default.registroRedesSociais.label" /> </p>
                    </div>
                    <div class="col-lg-12">
                        <oauth:connect provider="google" class="btn btn-material-red btn-lg btn-primary btn-block"><i class="fa fa-fw fa-google"></i>Google</oauth:connect>
                    </div>
                    <div class="col-lg-12">
                        <oauth:connect provider="twitter" class="btn btn-material-light-blue btn-lg btn-primary btn-block"><i class="fa fa-fw fa-twitter"></i>Twitter</oauth:connect>
                    </div>
                    <div class="col-lg-12">
                        <oauth:connect provider="facebook" class="btn btn-material-blue btn-lg btn-primary btn-block"><i class="fa fa-fw fa-facebook"></i>Facebook</oauth:connect>
                    </div>
                </g:if>
            </div>
        </div>
    </div>
</g:form>
</body>
</html>

grails-app/views/usuario/show.gsp
<%@ page import="arquitetura.seguranca.Usuario" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="show">
	<g:set var="entityName" value="${message(code: 'usuario.label', default: 'Usuario')}" scope="request" />
	<g:set var="entityNamePlural" value="${message(code: 'usuario.plural.label', default: 'Usuarios')}" scope="request" />
	<g:set var="instancia" value="${usuarioInstance}" scope="request" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.nomeCompleto.label" default="nomeCompleto" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:fieldValue bean="${usuarioInstance}" field="nomeCompleto"/>

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.email.label" default="email" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:fieldValue bean="${usuarioInstance}" field="email"/>

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.username.label" default="Username" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:fieldValue bean="${usuarioInstance}" field="username"/>

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.accountExpired.label" default="Account Expired" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:formatBoolean boolean="${usuarioInstance?.accountExpired}" />

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.accountLocked.label" default="Account Locked" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:formatBoolean boolean="${usuarioInstance?.accountLocked}" />

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.enabled.label" default="Enabled" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:formatBoolean boolean="${usuarioInstance?.enabled}" />

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuario.passwordExpired.label" default="Password Expired" />
	</label>
	<div class="col-lg-4">
		<p class="form-control-static">

			<g:formatBoolean boolean="${usuarioInstance?.passwordExpired}" />

		</p>
	</div>
</div>

<div class="form-group">
	<label class="col-lg-2 control-label">
		<g:message code="usuarioCommand.permissoes.label" default="Permissoes"/>
	</label>

	<div class="col-lg-4">
		<p class="form-control-static">

			<g:each in="${usuarioInstance.permissoes}" var="p">
				${p?.authority}<br />
			</g:each>

		</p>
	</div>
</div>
	
</body>
</html>