grails-app/domain/arquitetura/i18n/I18n.groovy
package arquitetura.i18n

class I18n {
    String key
    Locale language
    String value

    static mapping = {
        cache true
        columns {
            key index: 'idx_message_key'
            language index: 'idx_message_key'
        }
    }

    static constraints = {
        key unique: 'language', nullable: false, blank: false, maxSize: 200
        language nullable: false
        value nullable: false, maxSize: 200
    }

    String toString() {
        value
    }
}

grails-app/controllers/arquitetura/i18n/I18nController.groovy
package arquitetura.i18n

import base.BaseController
import net.sf.ehcache.Ehcache

class I18nController extends BaseController<I18n> {

    Ehcache messageCache
    def i18nService

    def getAtributoQuandoSalvoOuExcluido(def Object instancia) {
        return instancia.key
    }

    def popup() {
        I18n instancia = i18nService.consultar(params.key, request.locale)
        if (!instancia) {
            instancia = new I18n(params)
        }
        respond instancia
    }

    def internalSave(def instance) {
        messageCache.flush()
        super.internalSave(instance)
    }

    def salvarPopup() {
        I18n instancia = find()
        if (!instancia) {
            instancia = new I18n()
        }
        if (internalUpdate(instancia)) {
            respond instancia, view: '/layouts/texto', model: [mensagem: message(code: "default.saved.message", args: [message(code: "i18n.label"), getAtributoQuandoSalvoOuExcluido(instancia)])]
        } else {
            respond instancia.errors, view: 'popup'
        }
    }
}

grails-app/views/i18n/_form.gsp
<%@ page import="arquitetura.i18n.I18n" %>



<div class="form-group">
	<label for="key" class="col-lg-2 control-label">
		<g:message code="i18n.key.label" default="Key"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="key" maxlength="200" required="" value="${i18nInstance?.key}"/>

	</div>
</div>

<div class="form-group">
	<label for="language" class="col-lg-2 control-label">
		<g:message code="i18n.language.label" default="Language"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:localeSelect name="language" value="${i18nInstance?.language}"  />

	</div>
</div>

<div class="form-group">
	<label for="value" class="col-lg-2 control-label">
		<g:message code="i18n.value.label" default="Value"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="value" maxlength="200" required="" value="${i18nInstance?.value}"/>

	</div>
</div>

grails-app/views/i18n/create.gsp
<%@ page import="arquitetura.i18n.I18n" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="create">
		<g:set var="entityName" value="${message(code: 'i18n.label', default: 'I18n')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'i18n.plural.label', default: 'I18n')}" scope="request" />
		<g:set var="instancia" value="${i18nInstance}" scope="request" />
		<title><g:message code="default.create.label" args="[entityName]"/></title>
	</head>

	<body>
        <g:render template="form"/>
	</body>
</html>

grails-app/views/i18n/edit.gsp
<%@ page import="arquitetura.i18n.I18n" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="edit">
		<g:set var="entityName" value="${message(code: 'i18n.label', default: 'I18n')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'i18n.plural.label', default: 'I18n')}" scope="request" />
		<g:set var="instancia" value="${i18nInstance}" scope="request" />
		<title><g:message code="default.edit.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:hiddenField name="id" value="${i18nInstance?.id}" />
		<g:hiddenField name="version" value="${i18nInstance?.version}" />
		<g:render template="form"/>
	</body>
</html>

grails-app/views/i18n/list.gsp
<%@ page import="arquitetura.i18n.I18n" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="list">
		<g:set var="entityName" value="${message(code: 'i18n.label', default: 'I18n')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'i18n.plural.label', default: 'I18ns')}" scope="request" />
		<g:set var="domainName" value="arquitetura.i18n.I18n" scope="request" />
		%{--<g:set var="filterProperties" value=""/>--}%
		<title><g:message code="default.list.label" args="[entityNamePlural]" /></title>
	</head>

	<body>
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						
						<g:sortableColumn property="key" title="${message(code: 'i18n.key.label', default: 'Key')}" params="${filterParams}" />
						
						<g:sortableColumn property="language" title="${message(code: 'i18n.language.label', default: 'Language')}" params="${filterParams}" />
						
						<g:sortableColumn property="value" title="${message(code: 'i18n.value.label', default: 'Value')}" params="${filterParams}" />
						
						<th class="acoes"><g:message code="sistema.acoes.label" /> </th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${i18nInstanceList}" status="i" var="i18nInstance">
					<tr>
						
						<td><g:link action="show" id="${i18nInstance.id}">${fieldValue(bean: i18nInstance, field: "key")}</g:link></td>
						
						<td>${fieldValue(bean: i18nInstance, field: "language")}</td>
						
						<td>${fieldValue(bean: i18nInstance, field: "value")}</td>
						
						<td class="acoes">
							<will:editLink id="${i18nInstance.id}" />
							<will:deleteConfirmButton id="${i18nInstance.id}" />
						</td>
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>

		<div class="pagination">
			<g:paginate total="${i18nInstanceCount}" params="${filterParams}"/>
		</div>
	</body>
</html>

grails-app/views/i18n/popup.gsp
<%@ page import="arquitetura.i18n.I18n" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="popup">
		<g:set var="entityName" value="${message(code: 'i18n.label', default: 'I18n')}" />
		<g:set var="entityNamePlural" value="${message(code: 'i18n.plural.label', default: 'I18ns')}" />
        <g:set var="instancia" value="${i18nInstance}" />
		<title><g:message code="default.new.label" args="[entityName]" /></title>
	</head>
	<body>
		<div id="create-menu" class="container" role="main">
			<g:form action="salvarPopup" class="form-horizontal" role="form" >
                <g:hiddenField name="id" value="${i18nInstance?.id}" />
                <g:hiddenField name="version" value="${i18nInstance?.version}" />
			    <g:render template="form"/>

                <div class="action-buttons">
                    <will:submitButtonFlutuante action="salvarPopup" />
                </div>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/i18n/show.gsp
<%@ page import="arquitetura.i18n.I18n" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="show">
	<g:set var="entityName" value="${message(code: 'i18n.label', default: 'I18n')}" scope="request" />
	<g:set var="entityNamePlural" value="${message(code: 'i18n.plural.label', default: 'I18ns')}" scope="request" />
	<g:set var="instancia" value="${i18nInstance}" scope="request" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="i18n.key.label" default="Key" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${i18nInstance}" field="key"/>
				
			</p>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="i18n.language.label" default="Language" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${i18nInstance}" field="language"/>
				
			</p>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="i18n.value.label" default="Value" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${i18nInstance}" field="value"/>
				
			</p>
		</div>
	</div>
	
</body>
</html>