grails-app/domain/arquitetura/configuracao/Configuracao.groovy
package arquitetura.configuracao

import arquitetura.abilities.TimestampAbility

@grails.util.Mixin(TimestampAbility)
class Configuracao {
    String chave
    String valor

    static mapping = {
        cache true
        columns {
            chave index: 'idx_configuracao'
            valor index: 'idx_configuracao'
        }
    }

    static constraints = {
        chave unique: true
    }
}

grails-app/controllers/arquitetura/configuracao/ConfiguracaoController.groovy
package arquitetura.configuracao

import base.BaseController

class ConfiguracaoController extends BaseController<Configuracao> {
    def getAtributoQuandoSalvoOuExcluido(def instancia) {
        return instancia.chave
    }
}

grails-app/views/configuracao/_form.gsp
<%@ page import="arquitetura.configuracao.Configuracao" %>



<div class="form-group">
	<label for="chave" class="col-lg-2 control-label">
		<g:message code="configuracao.chave.label" default="Chave"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="chave" required="" value="${configuracaoInstance?.chave}"/>

	</div>
</div>

<div class="form-group">
	<label for="valor" class="col-lg-2 control-label">
		<g:message code="configuracao.valor.label" default="Valor"/>
		<span class="required-indicator">*</span>
	</label>
	<div class="col-lg-4">
		<will:textField name="valor" required="" value="${configuracaoInstance?.valor}"/>

	</div>
</div>

grails-app/views/configuracao/create.gsp
<%@ page import="arquitetura.configuracao.Configuracao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="create">
		<g:set var="entityName" value="${message(code: 'configuracao.label', default: 'Configuracao')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'configuracao.plural.label', default: 'Configuracao')}" scope="request" />
		<g:set var="instancia" value="${configuracaoInstance}" scope="request" />
		<title><g:message code="default.create.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:render template="form"/>
	</body>
</html>

grails-app/views/configuracao/edit.gsp
<%@ page import="arquitetura.configuracao.Configuracao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="edit">
		<g:set var="entityName" value="${message(code: 'configuracao.label', default: 'Configuracao')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'configuracao.plural.label', default: 'Configuracao')}" scope="request" />
		<g:set var="instancia" value="${configuracaoInstance}" scope="request" />
		<title><g:message code="default.edit.label" args="[entityName]"/></title>
	</head>

	<body>
		<g:hiddenField name="id" value="${configuracaoInstance?.id}" />
		<g:hiddenField name="version" value="${configuracaoInstance?.version}" />
		<g:render template="form"/>
	</body>
</html>

grails-app/views/configuracao/list.gsp
<%@ page import="arquitetura.configuracao.Configuracao" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="list">
		<g:set var="entityName" value="${message(code: 'configuracao.label', default: 'Configuracao')}" scope="request" />
		<g:set var="entityNamePlural" value="${message(code: 'configuracao.plural.label', default: 'Configuracaos')}" scope="request" />
		<g:set var="domainName" value="arquitetura.configuracao.Configuracao" scope="request" />
		%{--<g:set var="filterProperties" value=""/>--}%
		<title><g:message code="default.list.label" args="[entityNamePlural]" /></title>
	</head>

	<body>
		<div class="table-responsive">
			<table class="table table-striped table-hover">
				<thead>
					<tr>
						
						<g:sortableColumn property="chave" title="${message(code: 'configuracao.chave.label', default: 'Chave')}" params="${filterParams}" />
						
						<g:sortableColumn property="valor" title="${message(code: 'configuracao.valor.label', default: 'Valor')}" params="${filterParams}" />
						
						<th class="acoes"><g:message code="sistema.acoes.label" /> </th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${configuracaoInstanceList}" status="i" var="configuracaoInstance">
					<tr>
						
						<td><g:link action="show" id="${configuracaoInstance.id}">${fieldValue(bean: configuracaoInstance, field: "chave")}</g:link></td>
						
						<td>${fieldValue(bean: configuracaoInstance, field: "valor")}</td>
						
						<td class="acoes">
							<will:editLink id="${configuracaoInstance.id}" />
							<will:deleteConfirmButton id="${configuracaoInstance.id}" />
						</td>
					</tr>
				</g:each>
				</tbody>
			</table>
		</div>

		<div class="pagination">
			<g:paginate total="${configuracaoInstanceCount}" params="${filterParams}"/>
		</div>
	</body>
</html>

grails-app/views/configuracao/show.gsp
<%@ page import="arquitetura.configuracao.Configuracao" %>
<!DOCTYPE html>
<html>
<head>
	<meta name="layout" content="show">
	<g:set var="entityName" value="${message(code: 'configuracao.label', default: 'Configuracao')}" scope="request" />
	<g:set var="entityNamePlural" value="${message(code: 'configuracao.plural.label', default: 'Configuracaos')}" scope="request" />
	<g:set var="instancia" value="${configuracaoInstance}" scope="request" />
	<title><g:message code="default.show.label" args="[entityName]" /></title>
</head>

<body>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="configuracao.chave.label" default="Chave" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${configuracaoInstance}" field="chave"/>
				
			</p>
		</div>
	</div>
	
	<div class="form-group">
		<label class="col-lg-2 control-label">
			<g:message code="configuracao.valor.label" default="Valor" />
		</label>
		<div class="col-lg-4">
			<p class="form-control-static">
				
				<g:fieldValue bean="${configuracaoInstance}" field="valor"/>
				
			</p>
		</div>
	</div>
	
</body>
</html>